# Generated by Django 4.0.2 on 2022-02-04 03:49

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExt',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_birthdate', models.DateField()),
                ('user_bio', models.TextField()),
                ('user_friends', models.ManyToManyField(related_name='friends', to='readmore_app.UserExt')),
                ('user_pending_friends', models.ManyToManyField(related_name='pending_friends', to='readmore_app.UserExt')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(blank=True, max_length=10000)),
                ('notification_title', models.CharField(max_length=10000)),
                ('notification_time', models.DateTimeField(auto_now_add=True)),
                ('notification_link', models.CharField(blank=True, max_length=10000)),
                ('notification_link_text', models.CharField(blank=True, max_length=10000)),
                ('notification_message', models.TextField()),
                ('notification_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readmore_app.userext')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=100)),
                ('club_description', models.TextField(blank=True, default='This is my book club.')),
                ('club_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readmore_app.userext')),
                ('club_users', models.ManyToManyField(blank=True, related_name='users', to='readmore_app.UserExt')),
            ],
        ),
    ]
