# Generated by Django 3.2.7 on 2022-01-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmore_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userext',
            name='user_friends',
            field=models.ManyToManyField(related_name='friends', to='readmore_app.UserExt'),
        ),
    ]
