# Generated by Django 3.2.7 on 2022-02-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmore_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_isbn', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=1000)),
                ('book_genre', models.CharField(max_length=1000)),
                ('book_bookcover_picture_link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='club',
            name='club_description',
            field=models.TextField(blank=True),
        ),
    ]
