# Generated by Django 3.2.7 on 2022-02-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmore_app', '0002_auto_20220204_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_library',
            field=models.ManyToManyField(blank=True, related_name='library', to='readmore_app.Book'),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_users',
            field=models.ManyToManyField(related_name='users', to='readmore_app.UserExt'),
        ),
    ]
