# Generated by Django 3.2.7 on 2022-01-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmore_app', '0003_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userext',
            name='user_interests',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='userext',
            name='user_pending_friends',
            field=models.ManyToManyField(related_name='pending_friends', to='readmore_app.UserExt'),
        ),
    ]
