# Generated by Django 4.0.2 on 2022-02-04 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readmore_app', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=100)),
                ('club_description', models.TextField(blank=True, default='This is my book club.')),
                ('club_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readmore_app.userext')),
                ('club_users', models.ManyToManyField(blank=True, related_name='users', to='readmore_app.UserExt')),
            ],
        ),
    ]
