# Generated by Django 3.2.7 on 2022-02-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmore_app', '0003_auto_20220204_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_pending_invites',
            field=models.ManyToManyField(related_name='pending_invites', to='readmore_app.UserExt'),
        ),
    ]
