# Generated by Django 3.2.7 on 2022-02-13 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readmore_app', '0004_club_club_pending_invites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_time', models.DateTimeField(auto_now_add=True)),
                ('chat_message', models.TextField()),
                ('chat_user_sent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='readmore_app.userext')),
            ],
        ),
        migrations.AlterField(
            model_name='club',
            name='club_users',
            field=models.ManyToManyField(related_name='user_clubs', to='readmore_app.UserExt'),
        ),
        migrations.CreateModel(
            name='ClubChat',
            fields=[
                ('chat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='readmore_app.chat')),
                ('chat_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readmore_app.club')),
            ],
            bases=('readmore_app.chat',),
        ),
    ]
