# Generated by Django 3.2.7 on 2022-02-13 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readmore_app', '0005_auto_20220212_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chat_user_sent',
            new_name='chat_user',
        ),
    ]
