# Generated by Django 3.2.7 on 2022-02-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmore_app', '0006_rename_chat_user_sent_chat_chat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(default='chat', max_length=20),
        ),
    ]
