# Generated by Django 3.2.7 on 2022-02-22 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readmore_app', '0009_clubbook_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
