# Generated by Django 3.2.7 on 2022-03-01 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readmore_app', '0010_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.TextField()),
                ('post_text', models.TextField()),
                ('post_img', models.TextField(blank=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_likes', models.ManyToManyField(related_name='likes', to='readmore_app.UserExt')),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='readmore_app.userext')),
            ],
        ),
        migrations.CreateModel(
            name='ClubPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='readmore_app.post')),
                ('post_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readmore_app.club')),
            ],
            bases=('readmore_app.post',),
        ),
    ]
