# Generated by Django 4.0.2 on 2022-03-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmore_app', '0011_clubpost_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingLogBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13)),
            ],
        ),
        migrations.AddField(
            model_name='userext',
            name='user_reading_log',
            field=models.ManyToManyField(related_name='reading_log', to='readmore_app.ReadingLogBook'),
        ),
    ]
