# Generated by Django 3.2.7 on 2022-03-06 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readmore_app', '0013_readinglogbook_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='readmore_app.post')),
                ('post_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='readmore_app.post')),
            ],
            bases=('readmore_app.post',),
        ),
    ]
