# Generated by Django 3.2 on 2022-03-24 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readmore_app', '0015_profilepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='readmore_app.post')),
                ('post_isbn', models.TextField()),
            ],
            bases=('readmore_app.post',),
        ),
    ]
