# Generated by Django 3.2.7 on 2022-03-21 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readmore_app', '0015_profilepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PM',
            fields=[
                ('chat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='readmore_app.chat')),
                ('chat_pm_identifier', models.CharField(max_length=100)),
            ],
            bases=('readmore_app.chat',),
        ),
    ]
