# Generated by Django 3.2.7 on 2022-03-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readmore_app', '0016_pm'),
        ('readmore_app', '0017_reviewpost_post_rating'),
    ]

    operations = [
    ]
