# Generated by Django 4.0.2 on 2022-04-07 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readmore_app', '0018_merge_0016_pm_0017_reviewpost_post_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookForumPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='readmore_app.post')),
                ('post_isbn', models.TextField()),
            ],
            bases=('readmore_app.post',),
        ),
    ]
