# Generated by Django 3.2.7 on 2022-04-11 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readmore_app', '0019_bookforumpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_name', models.CharField(max_length=100)),
                ('meeting_description', models.TextField()),
                ('meeting_time', models.DateTimeField()),
                ('meeting_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readmore_app.club')),
            ],
        ),
    ]
