# Generated by Django 3.2.7 on 2022-04-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmore_app', '0020_meeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookforumpost',
            old_name='post_isbn',
            new_name='post_book_isbn',
        ),
        migrations.AlterField(
            model_name='userext',
            name='user_bio',
            field=models.TextField(default="This user hasn't written a bio :("),
        ),
    ]
