# Generated by Django 3.2.7 on 2022-04-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmore_app', '0021_auto_20220411_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_library',
            field=models.ManyToManyField(blank=True, related_name='clubs', to='readmore_app.ClubBook'),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_pending_invites',
            field=models.ManyToManyField(blank=True, related_name='pending_invites', to='readmore_app.UserExt'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='readmore_app.UserExt'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(blank=True),
        ),
    ]
